---
provider:
  name: azure
  waagent:
    version: 2.0.14
bootstrapper:
  mirror: http://httpredir.debian.org/debian/
  workspace: /target
image:
  name: debian-{system.release}-{system.architecture}-{%y}{%m}{%d}
  description: Debian {system.release} {system.architecture}
system:
  release: jessie
  architecture: amd64
  bootloader: grub
  charmap: UTF-8
  locale: en_US
  timezone: UTC
volume:
  backing: raw
  partitions:
    type: msdos
    root:
      filesystem: ext4
      size: 10GiB
packages:
  components:
  - main
  - contrib
  - non-free
plugins:
  ntp:
    servers:
    - time.windows.com
