---
name: disk
provider:
  name: gce
  description: Debian {system.release} {system.architecture}
bootstrapper:
  workspace: /target
system:
  release: wheezy
  architecture: amd64
  bootloader: grub
  charmap: UTF-8
  locale: en_US
  timezone: UTC
volume:
  backing: raw
  partitions:
    type: msdos
    root:
      filesystem: ext4
      size: 10GiB
packages:
  install:
    - rsync
    - screen
    - vim
plugins:
  google_cloud_sdk: {}
  ntp:
    servers:
    - metadata.google.internal
