---
name: debian-{system.release}-{system.architecture}-{%y}{%m}{%d}
provider:
  name: virtualbox
  guest_additions: /usr/share/virtualbox/VBoxGuestAdditions.iso
bootstrapper:
  workspace: /target
system:
  release: wheezy
  architecture: amd64
  bootloader: grub
  charmap: UTF-8
  hostname: localhost
  locale: en_US
  timezone: UTC
volume:
  backing: vmdk
  partitions:
    type: msdos
    boot:
      filesystem: ext2
      size: 64MiB
    root:
      filesystem: ext4
      size: 1856MiB
    swap:
      size: 128MiB
packages: {}
plugins:
  vagrant: {}
